sourcecode/Claim_project_v1.1/Complain/Complain/Controllers/AdminController.cs
using Complain.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Complain.Controllers
{
    public class AdminController : Controller
    {
        complain_databaseEntities db = new complain_databaseEntities();
        #region Log out destroy session
        [Authorize]
        public ActionResult Exit()
        {
            Session["account_id"] = null;
            Session["name"] = null;
            Session["faculty"] = null;
            Session["department"] =null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Login","Login");
        }
        #endregion

        #region Home page with list claim
        [Authorize]
        public ActionResult Index(int? page)
        {
                int department = int.Parse(Session["department"].ToString());
                int pageNumber = (page ?? 1);
                int pageSize = 10;
                if (department != 1 && department != 4)
                {
                    return View(db.Claims.Where(c => c.Id_department == department).ToList().OrderBy(n => n.Id_department).ToPagedList(pageNumber, pageSize));
                }
                else
                {
                    return View(db.Claims.ToList().OrderBy(n => n.Id_department).ToPagedList(pageNumber, pageSize));
                }                   
        }
        #endregion

        #region Count number claim with every status
        [Authorize]
        public ActionResult CountClaim()
        {
            int department = int.Parse(Session["department"].ToString());
            List<int> count = new List<int>();
            if(department != 1 && department != 4)
            {
                int success = (from c in db.Claims
                               where c.Status == 2 && c.Id_department == department
                               select c).Count();
                count.Add(success);

                int inprogress = (from c in db.Claims
                                  where c.Status == 1 && c.Id_department == department
                                  select c).Count();
                count.Add(inprogress);
                int waiting = (from c in db.Claims
                               where c.Status == 0 && c.Id_department == department
                               select c).Count();
                count.Add(waiting);


            }
            else
            {
                int waiting = (from c in db.Claims
                               where c.Status == 0 
                               select c).Count();               
                int inprogress = (from c in db.Claims
                                  where c.Status == 1
                                  select c).Count();            

                int success = (from c in db.Claims
                               where c.Status == 2 
                               select c).Count();
                count.Add(success);
                count.Add(inprogress);
                count.Add(waiting);
            }
            

            return PartialView(count);
        }

        #endregion

        #region Detail Claim
        public ActionResult DetailClaim(int id)
        {
                //update status
                Claim cl = db.Claims.SingleOrDefault(n => n.Id_claims == id);
                if(cl.Status !=2)
                {
                    cl.Status = 1;
                }              
                UpdateModel(cl);
                db.SaveChanges();
                if (cl == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                return View(cl);
        }
        [Authorize(Users = "2,3")]
        [HttpPost, ActionName("DetailClaim")]
        public ActionResult UpdateSuccess(int id)
        {        
                Claim cl = db.Claims.SingleOrDefault(n => n.Id_claims == id);
                cl.Status = 2;
                UpdateModel(cl);
                db.SaveChanges();
                return RedirectToAction("Index");
           
        }
        #endregion

        #region Edit Claim
        [Authorize(Users = "2,3")]
        [HttpGet]
        public ActionResult Edit(int id)
        {
                ViewBag.Id_department = new SelectList(db.Departments.Where(d => d.Id_department != 1 && d.Id_department != 4).ToList(), "Id_department", "Name");
                Claim cl = db.Claims.SingleOrDefault(n => n.Id_claims == id);
                if (cl == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                return View(cl);
        }
        [HttpPost]
        public ActionResult Edit(Claim cl, FormCollection a )
        {
            ViewBag.Id_department = new SelectList(db.Departments.Where(d => d.Id_department != 1 && d.Id_department != 4).ToList(), "Id_department", "Name");
            Claim cl_edit = db.Claims.SingleOrDefault(n => n.Id_claims == cl.Id_claims);
            UpdateModel(cl_edit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region Delete Claim
        [Authorize(Users = "2,3")]
        public ActionResult Delete(int id)
        {
                Claim cl = db.Claims.SingleOrDefault(n => n.Id_claims == id);
                if (cl == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                return View(cl);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
                Claim cl = db.Claims.SingleOrDefault(n => n.Id_claims == id);
                if (cl == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                db.Claims.Remove(cl);
                db.SaveChanges();
                return RedirectToAction("Index");
        }
        #endregion

        #region List Claim With Status
        [Authorize]
        public ActionResult ListStatus(int? page,int status)
        {
                int department = int.Parse(Session["department"].ToString());
                int pageNumber = (page ?? 1);
                int pageSize = 10;
                if (department != 1 && department != 4)
                {
                    return View(db.Claims.Where(c => c.Id_department == department && c.Status == status).ToList().OrderBy(n => n.Id_department).ToPagedList(pageNumber, pageSize));
                }
                else
                {
                    return View(db.Claims.Where(c => c.Status == status).ToList().OrderBy(n => n.Id_department).ToPagedList(pageNumber, pageSize));
                }
        }
        #endregion

        #region User Info
        [Authorize]
        [HttpGet]
        public ActionResult UserInfo()
        {
            int user_id = int.Parse(Session["account_id"].ToString());
            Account ac = db.Accounts.Where(acc => acc.Id_Account == user_id).SingleOrDefault();
            return View(ac);
        }
        #endregion

        #region List account
        [Authorize(Users ="2")]
        [HttpGet]
        public ActionResult ListAccount()
        {        
            return View(db.Accounts.ToList());
        }
        #endregion

        #region Edit account
        [Authorize(Users = "2")]
        [HttpGet]
        public ActionResult EditAccount(int id)
        {
            ViewBag.Id_department = new SelectList(db.Departments.ToList(), "Id_department", "Name");
            ViewBag.Id_faculty = new SelectList(db.Faculties.ToList(), "Id_faculty", "Name");
            Account ac = db.Accounts.SingleOrDefault(n => n.Id_Account == id);
            if (ac == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(ac);
        }
        [HttpPost]
        public ActionResult EditAccount(Account ac, FormCollection a)
        {
            ViewBag.Id_department = new SelectList(db.Departments.ToList(), "Id_department", "Name");
            ViewBag.Id_faculty = new SelectList(db.Faculties.ToList(), "Id_faculty", "Name");
            Account ac_edit = db.Accounts.SingleOrDefault(n => n.Id_Account == ac.Id_Account);
            UpdateModel(ac_edit);
            db.SaveChanges();
            return RedirectToAction("ListAccount");
        }
        #endregion

        #region Create Account
        [Authorize(Users = "2")]
        [HttpGet]
        public ActionResult CreateAccount()
        {
            ViewBag.Id_department = new SelectList(db.Departments.ToList(), "Id_department", "Name");
            ViewBag.Id_faculty = new SelectList(db.Faculties.ToList(), "Id_faculty", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult CreateAccount(Account ac)
        {
            db.Accounts.Add(ac);
            db.SaveChanges();
            return RedirectToAction("ListAccount");
        }
        #endregion

        #region detail account
        [Authorize(Users = "2")]
        public ActionResult DetailsAccount(int id)
        {           
            return View(db.Accounts.Where(ac=>ac.Id_Account==id).SingleOrDefault());
        }
        #endregion

        #region delete account
        [Authorize(Users = "2")]
        public ActionResult DeleteAccount(int id)
        {
            Account ac = db.Accounts.Where(acc => acc.Id_Account == id).SingleOrDefault();
            if (ac == null)
            {
                Response.StatusCode = 404;

sourcecode/Claim_project_v1.1/Complain/Complain/Controllers/StudentController.cs
using Complain.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Complain.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        complain_databaseEntities db = new complain_databaseEntities();
        // GET: Student
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Id_department = new SelectList(db.Departments.Where(d=>d.Id_department != 1 && d.Id_department != 4).ToList(), "Id_department", "Name");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Index(Claim cl, HttpPostedFileBase upload, FormCollection a)
        {
            ViewBag.Id_department = new SelectList(db.Departments.Where(d => d.Id_department != 1 && d.Id_department != 4).ToList(), "Id_department", "Name");
            cl.Id_Account = int.Parse(Session["account_id"].ToString());
            cl.CreateTime = DateTime.Now;
            var filename = Path.GetFileName(upload.FileName);
            var path = Path.Combine(Server.MapPath("~/file_pdf"), filename);
            string[] kt = filename.Split(new char[] { '.' });
            string head = kt[0].ToString();
            cl.Pdf = head + ".pdf";
            while (System.IO.File.Exists(path))
            {                              
                Random rd = new Random();
                string TextRd;
                TextRd = Convert.ToString((char)rd.Next(65, 90));
                cl.Pdf = head + TextRd + ".pdf";
                path = Path.Combine(Server.MapPath("~/file_pdf"), head + TextRd + ".pdf");
            }
            upload.SaveAs(path);
            cl.Status = 0;
            db.Claims.Add(cl);
            db.SaveChanges();
            return Content("<script language='javascript' type='text/javascript'>alert('Thanks for Feedback!'); window.location.href ='/Student/Index'; </script>");
        }
    }
}

sourcecode/Claim_project_v1.1/Complain/Complain/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Claim Admin</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/admin/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="~/Content/admin/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/Content/admin/admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="~/Content/admin/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/admin/font-awesome.min.css" rel="stylesheet" type="text/css">


</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p class="navbar-brand fa fa-user" style="font-size:20px;"> @Session["name"]</p>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="@Url.Action("UserInfo","Admin")"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li>
                    <a href="@Url.Action("Exit","Admin")"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Student")"><i class="fa fa-dashboard fa-fw"></i>Form Claim</a>
                        </li>
                        @if (Session["faculty"].ToString().Equals("2"))
                        {
                            <li>
                                <a href="@Url.Action("ListAccount","Admin")"><i class="fa fa-user  fa-fw"></i>Account</a>
                            </li>
                        }                      
                        <li>
                            <a href="#"><i class="fa fa-envelope-o  fa-fw"></i>Claim<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index", "Admin")">All</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("ListStatus", "Admin", new { status = 0})">Waiting</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("ListStatus", "Admin", new { status = 1})">In Progress</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("ListStatus", "Admin", new { status = 2})">Success</a>
                                </li>                               
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Claim</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
               @Html.Action("CountClaim","Admin")
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                      
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            @RenderBody()
                            <!-- /.row -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12-->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Scripts/admin/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/admin/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Scripts/admin/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="~/Scripts/admin/raphael.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Scripts/admin/admin.js"></script>

</body>

</html>